# Generated by Django 3.1.7 on 2021-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.CharField(max_length=50),
        ),
    ]
