# Generated by Django 3.1.7 on 2021-03-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_auto_20210329_0958'),
    ]

    def insert_default_ranks(apps, schema_editor):
        Rank = apps.get_model('bank_app', 'Rank')
        rank = Rank(name='Basic', value=1)
        rank.save()

    operations = [
        migrations.RunPython(insert_default_ranks),
    ]
